name: Zeus core - test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: npm install && npm run build
    - name: Run tests
      run: cd native/src/zeus_core && cargo test
