name: Zeus core - test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: npm install && npm run build
    - name: Run tests
      working-directory: ./native/src/zeus_core
      run: cargo test
    - name: Code coverage
      working-directory: ./native/src/zeus_core
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: ../../../coverage.sh
